server:
  port: 8080
  servlet:
    context-path: /graphic
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3406/aiPro?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 'root'

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto #
  mapper-locations: classpath:mapper/*.xml # XML